// Generated by lsc from publication-decisions.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

function publicationState(current: Option<string>, expected: string, revision: string): string
{
  if (match current { case Some(i_value) => (i_value == revision) case None => false }) then
    "complete"
  else
    if (match current { case Some(i_value) => (i_value == expected) case None => false }) then
      "pending"
    else
      match current {
        case Some(i_current_val) =>
          if (i_current_val == "") then
            "stale"
          else
            "inspect"
        case None =>
          "stale"
      }
}

lemma publicationState_ensures(current: Option<string>, expected: string, revision: string)
  ensures ((match current { case Some(i_value) => (i_value == revision) case None => false }) ==> (publicationState(current, expected, revision) == "complete"))
  ensures ((match current { case Some(i_value) => (i_value != revision) case None => true }) ==> (match current { case Some(i_value) => (i_value == expected) case None => false }) ==> (publicationState(current, expected, revision) == "pending"))
  ensures ((match current { case Some(i_) => false case None => true }) ==> (publicationState(current, expected, revision) == "stale"))
  ensures ((match current { case Some(i_value) => (i_value == "") case None => false }) ==> (match current { case Some(i_value) => (i_value != revision) case None => true }) ==> (match current { case Some(i_value) => (i_value != expected) case None => true }) ==> (publicationState(current, expected, revision) == "stale"))
  ensures (match current { case Some(i_current_val) => ((i_current_val != "") ==> (i_current_val != revision) ==> (i_current_val != expected) ==> (publicationState(current, expected, revision) == "inspect")) case None => true })
{
}

function sameConsolidation(before: Option<string>, after: Option<string>): bool
{
  match before {
    case Some(i_before_val) =>
      ((i_before_val != "") && (match after { case Some(i_value) => (i_value == i_before_val) case None => false }))
    case None =>
      false
  }
}

lemma sameConsolidation_ensures(before: Option<string>, after: Option<string>)
  ensures ((match before { case Some(i_) => false case None => true }) ==> !(sameConsolidation(before, after)))
  ensures (match before { case Some(i_before_val) => (sameConsolidation(before, after) == ((i_before_val != "") && (match after { case Some(i_value) => (i_value == i_before_val) case None => false }))) case None => true })
{
}
