// Generated by lsc from remote-policy.ts
// lsc options: string-semantics=javascript-utf16

datatype RemoteAddress = RemoteAddress(protocol: string, hostname: string, username: string, password: string, hash: string, search: string)

function localHttp(protocol: string, hostname: string): bool
{
  ((protocol == "http:") && (((hostname == "localhost") || (hostname == "127.0.0.1")) || (hostname == "[::1]")))
}

lemma localHttp_ensures(protocol: string, hostname: string)
  ensures (localHttp(protocol, hostname) == ((protocol == "http:") && (((hostname == "localhost") || (hostname == "127.0.0.1")) || (hostname == "[::1]"))))
{
}

function allowedRemote(url: RemoteAddress, whitespace: bool): bool
{
  (((((((url.protocol == "https:") || localHttp(url.protocol, url.hostname)) && (url.username == "")) && (url.password == "")) && (url.hash == "")) && (url.search == "")) && !(whitespace))
}

lemma allowedRemote_ensures(url: RemoteAddress, whitespace: bool)
  ensures (allowedRemote(url, whitespace) == (((((((url.protocol == "https:") || localHttp(url.protocol, url.hostname)) && (url.username == "")) && (url.password == "")) && (url.hash == "")) && (url.search == "")) && !(whitespace)))
{
}
