// Generated by lsc from sync-decisions.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

function automaticSyncReady(autoSync: bool, hasUploadTimer: bool): bool
{
  (autoSync && !(hasUploadTimer))
}

lemma automaticSyncReady_ensures(autoSync: bool, hasUploadTimer: bool)
  ensures (automaticSyncReady(autoSync, hasUploadTimer) == (autoSync && !(hasUploadTimer)))
{
}

function backgroundReady(connected: bool, layoutReady: bool): bool
{
  (connected && layoutReady)
}

lemma backgroundReady_ensures(connected: bool, layoutReady: bool)
  ensures (backgroundReady(connected, layoutReady) == (connected && layoutReady))
{
}

function captureReady(layoutReady: bool, attached: bool, hasEngine: bool): bool
{
  ((layoutReady && attached) && hasEngine)
}

lemma captureReady_ensures(layoutReady: bool, attached: bool, hasEngine: bool)
  ensures (captureReady(layoutReady, attached, hasEngine) == ((layoutReady && attached) && hasEngine))
{
}

function syncOutcome(success: bool, failed: bool, retryable: bool): string
{
  if failed then
    if retryable then
      "retry"
    else
      "stop"
  else
    if success then
      "success"
    else
      "stop"
}

lemma syncOutcome_ensures(success: bool, failed: bool, retryable: bool)
  ensures (failed ==> (syncOutcome(success, failed, retryable) == (if retryable then "retry" else "stop")))
  ensures (!(failed) ==> (syncOutcome(success, failed, retryable) == (if success then "success" else "stop")))
{
}

function installableJournal(current: Option<string>, original: Option<string>, migrated: Option<string>): bool
{
  (((match current { case Some(i_) => false case None => true }) || (current == original)) || (current == migrated))
}

lemma installableJournal_ensures(current: Option<string>, original: Option<string>, migrated: Option<string>)
  ensures (installableJournal(current, original, migrated) == (((match current { case Some(i_) => false case None => true }) || (current == original)) || (current == migrated)))
{
}
