// Generated by lsc from history-decisions.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

datatype DiffContent = DiffContent(name: string, contents: string)

datatype Snapshot = Snapshot(id: string, path: Option<string>, text: Option<string>, binary: bool, hash: string)

datatype Change = Change(kind: ChangeKind, baseline: Option<Snapshot>, local: Option<Snapshot>, incoming: Option<Snapshot>, result: Snapshot)

datatype ChangeKind = combined | local | incoming | synced

function diffFile(file: Option<Snapshot>): Option<DiffContent>
{
  match file {
    case Some(i_file_val) =>
      match i_file_val.path {
        case Some(i_file_path_val) =>
          match i_file_val.text {
            case Some(i_file_text_val) =>
              if (i_file_path_val == "") then
                None
              else
                Some(DiffContent(i_file_path_val, i_file_text_val))
            case None =>
              None
          }
        case None =>
          None
      }
    case None =>
      None
  }
}

lemma diffFile_ensures(file: Option<Snapshot>)
  ensures ((match file { case Some(i_) => false case None => true }) ==> (match diffFile(file) { case Some(i_) => false case None => true }))
  ensures (match file { case Some(i_file_val) => ((match diffFile(file) { case Some(i_) => false case None => true }) == (((match i_file_val.path { case Some(i_) => false case None => true }) || (match i_file_val.path { case Some(i_value) => (i_value == "") case None => false })) || (match i_file_val.text { case Some(i_) => false case None => true }))) case None => true })
  ensures (match file { case Some(i_file_val) => (match diffFile(file) { case Some(i_result_val) => ((match i_file_val.path { case Some(i_value) => (i_value == i_result_val.name) case None => false }) && (match i_file_val.text { case Some(i_value) => (i_value == i_result_val.contents) case None => false })) case None => true }) case None => true })
{
}

function fileName(change: Change): string
{
  match change.result.path {
    case Some(i_oc0_val) =>
      i_oc0_val
    case None =>
      baselineName(change.baseline)
  }
}

lemma fileName_ensures(change: Change)
  ensures (match change.result.path { case Some(i_change_result_path_val) => (fileName(change) == i_change_result_path_val) case None => true })
  ensures ((match change.result.path { case Some(i_) => false case None => true }) ==> (match change.baseline { case Some(i_) => false case None => true }) ==> (fileName(change) == "Deleted file"))
  ensures ((match change.result.path { case Some(i_) => false case None => true }) ==> (fileName(change) == baselineName(change.baseline)))
{
}

function visibleHash(file: Option<Snapshot>): Option<string>
{
  match file {
    case Some(i_file_val) =>
      if ((match i_file_val.path { case Some(i_) => false case None => true }) || (match i_file_val.path { case Some(i_value) => (i_value == "") case None => false })) then
        Option.None
      else
        Option.Some(i_file_val.hash)
    case None =>
      None
  }
}

lemma visibleHash_ensures(file: Option<Snapshot>)
  ensures ((match file { case Some(i_) => false case None => true }) ==> (match visibleHash(file) { case Some(i_) => false case None => true }))
  ensures (match file { case Some(i_file_val) => (visibleHash(file) == (if ((match i_file_val.path { case Some(i_) => false case None => true }) || (match i_file_val.path { case Some(i_value) => (i_value == "") case None => false })) then Option.None else Option.Some(i_file_val.hash))) case None => true })
{
}

function baselineName(file: Option<Snapshot>): string
{
  match file {
    case Some(i_file_val) =>
      match i_file_val.path {
        case Some(i_oc1_val) =>
          i_oc1_val
        case None =>
          "Deleted file"
      }
    case None =>
      "Deleted file"
  }
}

lemma baselineName_ensures(file: Option<Snapshot>)
  ensures ((match file { case Some(i_) => false case None => true }) ==> (baselineName(file) == "Deleted file"))
  ensures (match file { case Some(i_file_val) => ((match i_file_val.path { case Some(i_) => false case None => true }) ==> (baselineName(file) == "Deleted file")) case None => true })
  ensures (match file { case Some(i_file_val) => (match i_file_val.path { case Some(i_file_path_val) => (baselineName(file) == i_file_path_val) case None => true }) case None => true })
{
}

function isBinary(file: Option<Snapshot>): bool
{
  match file {
    case Some(i_file_val) =>
      i_file_val.binary
    case None =>
      false
  }
}

lemma isBinary_ensures(file: Option<Snapshot>)
  ensures ((match file { case Some(i_) => false case None => true }) ==> !(isBinary(file)))
  ensures (match file { case Some(i_file_val) => (isBinary(file) == i_file_val.binary) case None => true })
{
}

function hasBinary(change: Change): bool
{
  (((isBinary(change.baseline) || isBinary(change.local)) || isBinary(change.incoming)) || isBinary(Some(change.result)))
}

lemma hasBinary_ensures(change: Change)
  ensures (hasBinary(change) == (((isBinary(change.baseline) || isBinary(change.local)) || isBinary(change.incoming)) || isBinary(Some(change.result))))
{
}

function movedPath(baseline: Option<Snapshot>, result: Snapshot): bool
{
  match baseline {
    case Some(i_baseline_val) =>
      (i_baseline_val.path != result.path)
    case None =>
      true
  }
}

lemma movedPath_ensures(baseline: Option<Snapshot>, result: Snapshot)
  ensures ((match baseline { case Some(i_) => false case None => true }) ==> movedPath(baseline, result))
  ensures (match baseline { case Some(i_baseline_val) => (movedPath(baseline, result) == (i_baseline_val.path != result.path)) case None => true })
{
}

function contentsUnchanged(change: Change): bool
{
  (((visibleHash(change.baseline) == visibleHash(change.local)) && (visibleHash(change.baseline) == visibleHash(change.incoming))) && (visibleHash(change.baseline) == visibleHash(Some(change.result))))
}

lemma contentsUnchanged_ensures(change: Change)
  ensures (contentsUnchanged(change) == (((visibleHash(change.baseline) == visibleHash(change.local)) && (visibleHash(change.baseline) == visibleHash(change.incoming))) && (visibleHash(change.baseline) == visibleHash(Some(change.result)))))
{
}

function hasText(file: Option<Snapshot>): bool
{
  match file {
    case Some(i_file_val) =>
      var text := i_file_val.text;
      match text {
        case Some(i_text_val) =>
          (i_text_val != "")
        case None =>
          false
      }
    case None =>
      false
  }
}

lemma hasText_ensures(file: Option<Snapshot>)
  ensures ((match file { case Some(i_) => false case None => true }) ==> !(hasText(file)))
  ensures (match file { case Some(i_file_val) => ((match i_file_val.text { case Some(i_) => false case None => true }) ==> !(hasText(file))) case None => true })
  ensures (match file { case Some(i_file_val) => (match i_file_val.text { case Some(i_file_text_val) => (hasText(file) == (i_file_text_val != "")) case None => true }) case None => true })
{
}

function comparisonSummary(change: Change): Option<string>
{
  if hasBinary(change) then
    Some("Binary file. No preview available.")
  else
    if contentsUnchanged(change) then
      Some((if movedPath(change.baseline, change.result) then "File moved, contents unchanged." else "Contents unchanged."))
    else
      if (((hasText(change.baseline) || hasText(change.local)) || hasText(change.incoming)) || hasText(Some(change.result))) then
        None
      else
        Some((match change.result.path { case Some(i_change_result_path_val) => (if (i_change_result_path_val != "") then "Empty file added." else "Empty file removed.") case None => "Empty file removed." }))
}

lemma comparisonSummary_ensures(change: Change)
  ensures (hasBinary(change) ==> (match comparisonSummary(change) { case Some(i_value) => (i_value == "Binary file. No preview available.") case None => false }))
  ensures (!(hasBinary(change)) ==> contentsUnchanged(change) ==> (match comparisonSummary(change) { case Some(i_value) => (i_value == (if movedPath(change.baseline, change.result) then "File moved, contents unchanged." else "Contents unchanged.")) case None => false }))
  ensures (!(hasBinary(change)) ==> !(contentsUnchanged(change)) ==> (((hasText(change.baseline) || hasText(change.local)) || hasText(change.incoming)) || hasText(Some(change.result))) ==> (match comparisonSummary(change) { case Some(i_) => false case None => true }))
  ensures (!(hasBinary(change)) ==> !(contentsUnchanged(change)) ==> !(hasText(change.baseline)) ==> !(hasText(change.local)) ==> !(hasText(change.incoming)) ==> !(hasText(Some(change.result))) ==> (match comparisonSummary(change) { case Some(i_value) => (i_value == (match change.result.path { case Some(i_change_result_path_val) => (if (i_change_result_path_val != "") then "Empty file added." else "Empty file removed.") case None => "Empty file removed." })) case None => false }))
{
}

function previewMatches(file: Option<Snapshot>, result: Snapshot): bool
{
  match file {
    case Some(i_file_val) =>
      ((i_file_val.path == result.path) && (i_file_val.text == result.text))
    case None =>
      false
  }
}

lemma previewMatches_ensures(file: Option<Snapshot>, result: Snapshot)
  ensures ((match file { case Some(i_) => false case None => true }) ==> !(previewMatches(file, result)))
  ensures (match file { case Some(i_file_val) => (previewMatches(file, result) == ((i_file_val.path == result.path) && (i_file_val.text == result.text))) case None => true })
{
}
