// Generated by lsc from issue-values.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

datatype IssueCopy = IssueCopy(title: string, message: string, details: string)

function issueValue(kind: string, detail: Option<string>): IssueCopy
{
  var details := ((("Gitbin: " + kind) + "\u000A") + (match detail { case Some(i_oc0_val) => i_oc0_val case None => "Saved data could not be validated." }));
  if (kind == "migration-required") then
    IssueCopy("Migration required", "Sync is currently paused due to pending migrations, please consolidate the repository", details)
  else
    if (kind == "newer-format") then
      IssueCopy("Update required", "This vault requires a newer Gitbin version. Update the plugin to continue.", details)
    else
      IssueCopy("Cannot read sync data", "Gitbin couldn\u2019t read its saved sync data. Your vault files haven\u2019t been changed.", details)
}

lemma issueValue_ensures(kind: string, detail: Option<string>)
  ensures (issueValue(kind, detail).details == ((("Gitbin: " + kind) + "\u000A") + (match detail { case Some(i_detail_val) => i_detail_val case None => "Saved data could not be validated." })))
  ensures ((kind == "migration-required") ==> ((issueValue(kind, detail).title == "Migration required") && (issueValue(kind, detail).message == "Sync is currently paused due to pending migrations, please consolidate the repository")))
  ensures ((kind == "newer-format") ==> ((issueValue(kind, detail).title == "Update required") && (issueValue(kind, detail).message == "This vault requires a newer Gitbin version. Update the plugin to continue.")))
  ensures ((kind != "migration-required") ==> (kind != "newer-format") ==> ((issueValue(kind, detail).title == "Cannot read sync data") && (issueValue(kind, detail).message == "Gitbin couldn\u2019t read its saved sync data. Your vault files haven\u2019t been changed.")))
{
}
