// Generated by lsc from status-decisions.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

function syncBlocked(kind: Option<string>): bool
{
  ((match kind { case Some(i_value) => (i_value == "migration-required") case None => false }) || (match kind { case Some(i_value) => (i_value == "newer-format") case None => false }))
}

lemma syncBlocked_ensures(kind: Option<string>)
  ensures (syncBlocked(kind) == ((match kind { case Some(i_value) => (i_value == "migration-required") case None => false }) || (match kind { case Some(i_value) => (i_value == "newer-format") case None => false })))
{
}

function repositoryState(hasCurrent: bool, changed: Option<bool>, hasSync: bool): string
{
  if (hasCurrent && (match changed { case Some(i_) => false case None => true })) then
    "Not verified"
  else
    if (hasCurrent && (match changed { case Some(i_value) => (i_value == true) case None => false })) then
      "Files waiting to sync"
    else
      if hasSync then
        "All changes synced"
      else
        "Connected"
}

lemma repositoryState_ensures(hasCurrent: bool, changed: Option<bool>, hasSync: bool)
  ensures (hasCurrent ==> (match changed { case Some(i_) => false case None => true }) ==> (repositoryState(hasCurrent, changed, hasSync) == "Not verified"))
  ensures (hasCurrent ==> (match changed { case Some(i_value) => (i_value == true) case None => false }) ==> (repositoryState(hasCurrent, changed, hasSync) == "Files waiting to sync"))
  ensures ((!(hasCurrent) || (match changed { case Some(i_value) => (i_value == false) case None => false })) ==> (repositoryState(hasCurrent, changed, hasSync) == (if hasSync then "All changes synced" else "Connected")))
{
}

function syncState(connected: bool, error: bool, issue: Option<string>, status: string, stale: bool, pending: bool, repository: string): string
{
  if !(connected) then
    "Not connected"
  else
    if error then
      match issue {
        case Some(i_issue_val) =>
          i_issue_val
        case None =>
          "Last sync failed"
      }
    else
      if (status == "Syncing\u2026") then
        "Syncing your changes"
      else
        if stale then
          if (|status| >= |"Offline"| && status[..|"Offline"|] == "Offline") then
            "Working offline"
          else
            "Last known state"
        else
          if pending then
            "Files waiting to sync"
          else
            repository
}

lemma syncState_ensures(connected: bool, error: bool, issue: Option<string>, status: string, stale: bool, pending: bool, repository: string)
  ensures (!(connected) ==> (syncState(connected, error, issue, status, stale, pending, repository) == "Not connected"))
  ensures (connected ==> error ==> (syncState(connected, error, issue, status, stale, pending, repository) == (match issue { case Some(i_issue_val) => i_issue_val case None => "Last sync failed" })))
  ensures (connected ==> !(error) ==> (status == "Syncing\u2026") ==> (syncState(connected, error, issue, status, stale, pending, repository) == "Syncing your changes"))
  ensures (connected ==> !(error) ==> (status != "Syncing\u2026") ==> stale ==> (syncState(connected, error, issue, status, stale, pending, repository) == (if (|status| >= |"Offline"| && status[..|"Offline"|] == "Offline") then "Working offline" else "Last known state")))
  ensures (connected ==> !(error) ==> (status != "Syncing\u2026") ==> !(stale) ==> (syncState(connected, error, issue, status, stale, pending, repository) == (if pending then "Files waiting to sync" else repository)))
{
}

function statusDescription(issue: Option<string>, error: Option<string>, manual: Option<string>): Option<string>
{
  match (match issue { case Some(i_oc0_val) => Option.Some(i_oc0_val) case None => error }) {
    case Some(i_oc1_val) =>
      Option.Some(i_oc1_val)
    case None =>
      manual
  }
}

lemma statusDescription_ensures(issue: Option<string>, error: Option<string>, manual: Option<string>)
  ensures (match issue { case Some(i_issue_val) => (match statusDescription(issue, error, manual) { case Some(i_value) => (i_value == i_issue_val) case None => false }) case None => true })
  ensures (match error { case Some(i_error_val) => ((match issue { case Some(i_) => false case None => true }) ==> (match statusDescription(issue, error, manual) { case Some(i_value) => (i_value == i_error_val) case None => false })) case None => true })
  ensures ((match issue { case Some(i_) => false case None => true }) ==> (match error { case Some(i_) => false case None => true }) ==> (statusDescription(issue, error, manual) == manual))
{
}

function acknowledgementsAccepted(values: seq<bool>): bool
{
  !((exists value :: value in values && !(value)))
}

lemma acknowledgementsAccepted_ensures(values: seq<bool>)
  ensures (acknowledgementsAccepted(values) == !((false in values)))
{
}

function statusColor(warning: bool, status: string): Option<string>
{
  if warning then
    Option.Some("gitbin-status-warning")
  else
    if (status == "All changes synced") then
      Option.Some("gitbin-status-current")
    else
      Option.None
}

lemma statusColor_ensures(warning: bool, status: string)
  ensures (warning ==> (match statusColor(warning, status) { case Some(i_value) => (i_value == "gitbin-status-warning") case None => false }))
  ensures (!(warning) ==> (statusColor(warning, status) == (if (status == "All changes synced") then Option.Some("gitbin-status-current") else Option.None)))
{
}

function manualStatus(failed: bool, storedError: bool, status: string): string
{
  if (failed && !(storedError)) then
    "Last sync failed"
  else
    status
}

lemma manualStatus_ensures(failed: bool, storedError: bool, status: string)
  ensures (manualStatus(failed, storedError, status) == (if (failed && !(storedError)) then "Last sync failed" else status))
{
}
