// Generated by lsc from credential-decisions.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

datatype Credential = Credential(type_: string, username: string, password: string)

datatype SavedAuthentication = SavedAuthentication(remote: string, credentials: Option<Credential>)

function credentialScope(expectedOrigin: string, expectedPath: string, origin: string, path: string): bool
{
  ((expectedOrigin == origin) && (expectedPath == path))
}

lemma credentialScope_ensures(expectedOrigin: string, expectedPath: string, origin: string, path: string)
  ensures (credentialScope(expectedOrigin, expectedPath, origin, path) == ((expectedOrigin == origin) && (expectedPath == path)))
{
}

function matchingSavedCredentials(remote: string, username: string, saved: Option<SavedAuthentication>): Option<Credential>
{
  match saved {
    case Some(i_saved_val) =>
      if (i_saved_val.remote != remote) then
        None
      else
        var credentials := i_saved_val.credentials;
        match credentials {
          case Some(i_credentials_val) =>
            if (i_credentials_val.username == username) then
              Option.Some(i_credentials_val)
            else
              Option.None
          case None =>
            None
        }
    case None =>
      None
  }
}

lemma matchingSavedCredentials_ensures(remote: string, username: string, saved: Option<SavedAuthentication>)
  ensures ((match saved { case Some(i_) => false case None => true }) ==> (match matchingSavedCredentials(remote, username, saved) { case Some(i_) => false case None => true }))
  ensures (match saved { case Some(i_saved_val) => ((i_saved_val.remote != remote) ==> (match matchingSavedCredentials(remote, username, saved) { case Some(i_) => false case None => true })) case None => true })
  ensures (match saved { case Some(i_saved_val) => ((i_saved_val.remote == remote) ==> (match i_saved_val.credentials { case Some(i_) => false case None => true }) ==> (match matchingSavedCredentials(remote, username, saved) { case Some(i_) => false case None => true })) case None => true })
  ensures (match saved { case Some(i_saved_val) => ((i_saved_val.remote == remote) ==> (match i_saved_val.credentials { case Some(i_saved_credentials_val) => (matchingSavedCredentials(remote, username, saved) == (if (i_saved_credentials_val.username == username) then Option.Some(i_saved_credentials_val) else Option.None)) case None => true })) case None => true })
{
}
