// Generated by lsc from content-values.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

datatype FileContent = FileContent(type_: string, value: string)

function textContent(value: string): FileContent
{
  FileContent("text", value)
}

lemma textContent_ensures(value: string)
  ensures (textContent(value).type_ == "text")
  ensures (textContent(value).value == value)
{
}

function equalContent(left: Option<FileContent>, right: Option<FileContent>): bool
{
  match left {
    case Some(i_left_val) =>
      match right {
        case Some(i_right_val) =>
          ((i_left_val.type_ == i_right_val.type_) && (i_left_val.value == i_right_val.value))
        case None =>
          false
      }
    case None =>
      match right {
        case Some(i_) =>
          false
        case None =>
          true
      }
  }
}

lemma equalContent_ensures(left: Option<FileContent>, right: Option<FileContent>)
  ensures ((match left { case Some(i_) => false case None => true }) ==> (equalContent(left, right) == (match right { case Some(i_) => false case None => true })))
  ensures ((match right { case Some(i_) => false case None => true }) ==> (equalContent(left, right) == (match left { case Some(i_) => false case None => true })))
  ensures (match left { case Some(i_left_val) => (match right { case Some(i_right_val) => (equalContent(left, right) == ((i_left_val.type_ == i_right_val.type_) && (i_left_val.value == i_right_val.value))) case None => true }) case None => true })
{
}
