// Generated by lsc from decisions.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

function SeqFind<T>(s: seq<T>, p: T -> bool): Option<T>
  ensures SeqFind(s, p).Some? ==> p(SeqFind(s, p).value)
  ensures SeqFind(s, p).Some? ==> SeqFind(s, p).value in s
  ensures SeqFind(s, p).Some? ==>
    exists i: nat :: i < |s| && s[i] == SeqFind(s, p).value && p(s[i]) &&
                     (forall j: nat :: j < i ==> !p(s[j]))
  ensures SeqFind(s, p).None? ==> forall i :: 0 <= i < |s| ==> !p(s[i])
  decreases |s|
{
  if |s| == 0 then None
  else if p(s[0]) then Some(s[0])
  else SeqFind(s[1..], p)
}

datatype ConnectionIdentity = ConnectionIdentity(remote: string, root: string, username: string, commitEmail: string, secretId: string)

datatype Snapshot = Snapshot(id: string, path: Option<string>, text: Option<string>, binary: bool, hash: string)

datatype ChangeKind = combined | local | incoming | synced

datatype Change = Change(kind: ChangeKind, baseline: Option<Snapshot>, local: Option<Snapshot>, incoming: Option<Snapshot>, result: Snapshot)

datatype MigrationSequence = supported | newer | invalid

function connectionChanged(left: ConnectionIdentity, right: ConnectionIdentity): bool
{
  (((((left.remote != right.remote) || (left.root != right.root)) || (left.username != right.username)) || (left.commitEmail != right.commitEmail)) || (left.secretId != right.secretId))
}

lemma connectionChanged_ensures(left: ConnectionIdentity, right: ConnectionIdentity)
  ensures (connectionChanged(left, right) == (((((left.remote != right.remote) || (left.root != right.root)) || (left.username != right.username)) || (left.commitEmail != right.commitEmail)) || (left.secretId != right.secretId)))
{
}

function same(left: Option<Snapshot>, right: Option<Snapshot>): bool
{
  match left {
    case Some(i_left_val) =>
      match right {
        case Some(i_right_val) =>
          ((i_left_val.path == i_right_val.path) && (i_left_val.hash == i_right_val.hash))
        case None =>
          false
      }
    case None =>
      match right {
        case Some(i_) =>
          false
        case None =>
          true
      }
  }
}

lemma same_ensures(left: Option<Snapshot>, right: Option<Snapshot>)
  ensures ((match left { case Some(i_) => false case None => true }) ==> (same(left, right) == (match right { case Some(i_) => false case None => true })))
  ensures ((match right { case Some(i_) => false case None => true }) ==> (same(left, right) == (match left { case Some(i_) => false case None => true })))
  ensures (match left { case Some(i_left_val) => (match right { case Some(i_right_val) => (same(left, right) == ((i_left_val.path == i_right_val.path) && (i_left_val.hash == i_right_val.hash))) case None => true }) case None => true })
{
}

function changeKind(baseline: Option<Snapshot>, local: Option<Snapshot>, incoming: Option<Snapshot>, known: bool): ChangeKind
{
  if !(known) then
    ChangeKind.synced
  else
    var localChanged := !(same(baseline, local));
    var incomingChanged := !(same(baseline, incoming));
    if ((localChanged && incomingChanged) && !(same(local, incoming))) then
      ChangeKind.combined
    else
      if incomingChanged then
        ChangeKind.incoming
      else
        ChangeKind.local
}

lemma changeKind_ensures(baseline: Option<Snapshot>, local: Option<Snapshot>, incoming: Option<Snapshot>, known: bool)
  ensures (!(known) ==> changeKind(baseline, local, incoming, known).synced?)
  ensures (known ==> !(same(baseline, local)) ==> !(same(baseline, incoming)) ==> !(same(local, incoming)) ==> changeKind(baseline, local, incoming, known).combined?)
  ensures (known ==> ((same(baseline, local) || same(baseline, incoming)) || same(local, incoming)) ==> (changeKind(baseline, local, incoming, known) == (if same(baseline, incoming) then ChangeKind.local else ChangeKind.incoming)))
{
}

function describeChange(baseline: Option<Snapshot>, local: Option<Snapshot>, incoming: Option<Snapshot>, result: Snapshot, known: bool): Option<Change>
{
  if ((known && same(baseline, Some(result))) && same(local, incoming)) then
    None
  else
    if (!(known) && (match result.path { case Some(i_) => false case None => true })) then
      None
    else
      Some(Change(changeKind(baseline, local, incoming, known), baseline, local, incoming, result))
}

lemma describeChange_ensures(baseline: Option<Snapshot>, local: Option<Snapshot>, incoming: Option<Snapshot>, result: Snapshot, known: bool)
  ensures ((match describeChange(baseline, local, incoming, result, known) { case Some(i_) => false case None => true }) == (((known && same(baseline, Some(result))) && same(local, incoming)) || (!(known) && (match result.path { case Some(i_) => false case None => true }))))
  ensures (match describeChange(baseline, local, incoming, result, known) { case Some(i_result_val) => (((((i_result_val.baseline == baseline) && (i_result_val.local == local)) && (i_result_val.incoming == incoming)) && (i_result_val.result == result)) && (i_result_val.kind == changeKind(baseline, local, incoming, known))) case None => true })
{
}

function ownerAt(owners: seq<string>, key: string): Option<string>
{
  SeqFind(owners, (existing: string) => (((existing == key) || (|existing| >= |(key + "/")| && existing[..|(key + "/")|] == (key + "/"))) || (|key| >= |(existing + "/")| && key[..|(existing + "/")|] == (existing + "/"))))
}

lemma ownerAt_ensures(owners: seq<string>, key: string)
  ensures (match ownerAt(owners, key) { case Some(i_result_val) => ((i_result_val in owners) && (((i_result_val == key) || (|i_result_val| >= |(key + "/")| && i_result_val[..|(key + "/")|] == (key + "/"))) || (|key| >= |(i_result_val + "/")| && key[..|(i_result_val + "/")|] == (i_result_val + "/")))) case None => true })
  ensures ((match ownerAt(owners, key) { case Some(i_) => false case None => true }) == forall i: int :: ((0 <= i) ==> (i < |owners|) ==> !((((owners[i] == key) || (|owners[i]| >= |(key + "/")| && owners[i][..|(key + "/")|] == (key + "/"))) || (|key| >= |(owners[i] + "/")| && key[..|(owners[i] + "/")|] == (owners[i] + "/"))))))
  ensures (match ownerAt(owners, key) { case Some(i_result_val) => exists i: int :: (((((0 <= i) && (i < |owners|)) && (owners[i] == i_result_val)) && (((owners[i] == key) || (|owners[i]| >= |(key + "/")| && owners[i][..|(key + "/")|] == (key + "/"))) || (|key| >= |(owners[i] + "/")| && key[..|(owners[i] + "/")|] == (owners[i] + "/")))) && forall j: int :: ((0 <= j) ==> (j < i) ==> !((((owners[j] == key) || (|owners[j]| >= |(key + "/")| && owners[j][..|(key + "/")|] == (key + "/"))) || (|key| >= |(owners[j] + "/")| && key[..|(owners[j] + "/")|] == (owners[j] + "/")))))) case None => true })
{
}

method migrationSequence(applied: seq<string>, expected: seq<string>) returns (res: MigrationSequence)
  ensures (res.newer? == exists i: int :: (((0 <= i) && (i < |applied|)) && !((applied[i] in expected))))
  ensures (res.supported? == ((|applied| <= |expected|) && forall i: int :: ((0 <= i) ==> (i < |applied|) ==> (applied[i] == expected[i]))))
  ensures (res.invalid? == ((forall i: int :: ((0 <= i) ==> (i < |applied|) ==> (applied[i] in expected))) && !(((|applied| <= |expected|) && forall i: int :: ((0 <= i) ==> (i < |applied|) ==> (applied[i] == expected[i]))))))
{
  if (exists id :: id in applied && !((id in expected))) {
    return MigrationSequence.newer;
  }
  if (|applied| > |expected|) {
    return MigrationSequence.invalid;
  }
  var index := 0;
  while (index < |applied|)
    invariant (0 <= index)
    invariant (index <= |applied|)
    invariant forall j: int :: ((0 <= j) ==> (j < index) ==> (applied[j] == expected[j]))
    decreases (|applied| - index)
  {
    if (applied[index] != expected[index]) {
      return MigrationSequence.invalid;
    }
    index := (index + 1);
  }
  return MigrationSequence.supported;
}
