// Generated by lsc from history-values.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

type Change(==)

type Snapshot(==)

datatype HistoryRecord = HistoryRecord(id: string, at: int, revision: Option<string>, baselineKnown: bool, changes: seq<Change>)

datatype HistoryValue = HistoryValue(checkpoint: Option<seq<Snapshot>>, entries: seq<HistoryRecord>)

function emptyHistory(): HistoryValue
{
  HistoryValue(None, [])
}

lemma emptyHistory_ensures()
  ensures (match emptyHistory().checkpoint { case Some(i_) => false case None => true })
  ensures (|emptyHistory().entries| == 0)
{
}
