// Generated by lsc from metadata-values.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

datatype MetadataValue = MetadataValue(consolidationHash: Option<string>, appliedMigrations: seq<string>)

function metadataValue(consolidationHash: Option<string>, appliedMigrations: seq<string>): MetadataValue
{
  MetadataValue(consolidationHash, appliedMigrations)
}

lemma metadataValue_ensures(consolidationHash: Option<string>, appliedMigrations: seq<string>)
  ensures (metadataValue(consolidationHash, appliedMigrations).consolidationHash == consolidationHash)
  ensures (metadataValue(consolidationHash, appliedMigrations).appliedMigrations == appliedMigrations)
{
}
