// Generated by lsc from path-rules.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

function StringIndexOf(s: string, sub: string): int
  ensures StringIndexOf(s, sub) == -1
       || (0 <= StringIndexOf(s, sub) <= |s| - |sub| && s[StringIndexOf(s, sub)..StringIndexOf(s, sub) + |sub|] == sub)
{
  StringIndexOfFrom(s, sub, 0)
}

function StringIndexOfFrom(s: string, sub: string, from: int): int
  ensures StringIndexOfFrom(s, sub, from) == -1
       || (0 <= StringIndexOfFrom(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFrom(s, sub, from)..StringIndexOfFrom(s, sub, from) + |sub|] == sub
           && StringIndexOfFrom(s, sub, from) >= from)
{
  StringIndexOfFromN(s, sub, if from < 0 then 0 else from)
}

function StringIndexOfFromN(s: string, sub: string, from: nat): int
  decreases |s| - from
  ensures StringIndexOfFromN(s, sub, from) == -1
       || (from <= StringIndexOfFromN(s, sub, from) <= |s| - |sub|
           && s[StringIndexOfFromN(s, sub, from)..StringIndexOfFromN(s, sub, from) + |sub|] == sub)
{
  if from + |sub| > |s| then -1
  else if s[from..from + |sub|] == sub then from as int
  else StringIndexOfFromN(s, sub, from + 1)
}

function invalidSegment(part: string): bool
{
  (((part == "..") || (part == ".")) || (part == ""))
}

lemma invalidSegment_ensures(part: string)
  ensures (invalidSegment(part) == (((part == "..") || (part == ".")) || (part == "")))
{
}

function traversalPath(path: string): bool
{
  ((((((invalidSegment(path) || (|path| >= |"./"| && path[..|"./"|] == "./")) || (|path| >= |"../"| && path[..|"../"|] == "../")) || (|path| >= |"/."| && path[|path|-|"/."|..] == "/.")) || (|path| >= |"/.."| && path[|path|-|"/.."|..] == "/..")) || (StringIndexOf(path, "/./") >= 0)) || (StringIndexOf(path, "/../") >= 0))
}

lemma traversalPath_ensures(path: string)
  ensures (traversalPath(path) == ((((((invalidSegment(path) || (|path| >= |"./"| && path[..|"./"|] == "./")) || (|path| >= |"../"| && path[..|"../"|] == "../")) || (|path| >= |"/."| && path[|path|-|"/."|..] == "/.")) || (|path| >= |"/.."| && path[|path|-|"/.."|..] == "/..")) || (StringIndexOf(path, "/./") >= 0)) || (StringIndexOf(path, "/../") >= 0)))
{
}

function safeStoragePath(path: string): bool
{
  ((((!(traversalPath(path)) && !((|path| >= |"/"| && path[..|"/"|] == "/"))) && !((|path| >= |"/"| && path[|path|-|"/"|..] == "/"))) && !((StringIndexOf(path, "//") >= 0))) && !((StringIndexOf(path, "\\") >= 0)))
}

lemma safeStoragePath_ensures(path: string)
  ensures (safeStoragePath(path) == ((((!(traversalPath(path)) && !((|path| >= |"/"| && path[..|"/"|] == "/"))) && !((|path| >= |"/"| && path[|path|-|"/"|..] == "/"))) && !((StringIndexOf(path, "//") >= 0))) && !((StringIndexOf(path, "\\") >= 0))))
{
}

function hiddenPath(path: string): bool
{
  ((|path| >= |"."| && path[..|"."|] == ".") || (StringIndexOf(path, "/.") >= 0))
}

lemma hiddenPath_ensures(path: string)
  ensures (hiddenPath(path) == ((|path| >= |"."| && path[..|"."|] == ".") || (StringIndexOf(path, "/.") >= 0)))
{
}

function metadataEntry(path: string): bool
{
  ((path == ".gitbin") || (|path| >= |".gitbin/"| && path[..|".gitbin/"|] == ".gitbin/"))
}

lemma metadataEntry_ensures(path: string)
  ensures (metadataEntry(path) == ((path == ".gitbin") || (|path| >= |".gitbin/"| && path[..|".gitbin/"|] == ".gitbin/")))
{
}

function overlaps(left: string, right: string): bool
{
  (((left == right) || (|left| >= |(right + "/")| && left[..|(right + "/")|] == (right + "/"))) || (|right| >= |(left + "/")| && right[..|(left + "/")|] == (left + "/")))
}

lemma overlaps_ensures(left: string, right: string)
  ensures (overlaps(left, right) == (((left == right) || (|left| >= |(right + "/")| && left[..|(right + "/")|] == (right + "/"))) || (|right| >= |(left + "/")| && right[..|(left + "/")|] == (left + "/"))))
  ensures (overlaps(left, right) == overlaps(right, left))
{
}

function stateLocation(root: string, id: string, binary: bool): string
{
  ((((".gitbin/vaults/" + root) + (if binary then "/attachments/" else "/notes/")) + id) + ".bin")
}

lemma stateLocation_ensures(root: string, id: string, binary: bool)
  ensures (binary ==> (stateLocation(root, id, binary) == ((((".gitbin/vaults/" + root) + "/attachments/") + id) + ".bin")))
  ensures (!(binary) ==> (stateLocation(root, id, binary) == ((((".gitbin/vaults/" + root) + "/notes/") + id) + ".bin")))
{
}

function safeSnapshotPath(path: string): bool
{
  ((((safeStoragePath(path) && (path != ".git")) && !((|path| >= |".git/"| && path[..|".git/"|] == ".git/"))) && !((|path| >= |"/.git"| && path[|path|-|"/.git"|..] == "/.git"))) && !((StringIndexOf(path, "/.git/") >= 0)))
}

lemma safeSnapshotPath_ensures(path: string)
  ensures (safeSnapshotPath(path) == ((((safeStoragePath(path) && (path != ".git")) && !((|path| >= |".git/"| && path[..|".git/"|] == ".git/"))) && !((|path| >= |"/.git"| && path[|path|-|"/.git"|..] == "/.git"))) && !((StringIndexOf(path, "/.git/") >= 0))))
{
}

function renamedPath(baseline: Option<string>, previous: string, next: string): Option<string>
{
  match baseline {
    case Some(i_baseline_val) =>
      if (i_baseline_val == previous) then
        Some(next)
      else
        if (|i_baseline_val| >= |(previous + "/")| && i_baseline_val[..|(previous + "/")|] == (previous + "/")) then
          Some((next + i_baseline_val[|previous|..]))
        else
          None
    case None =>
      None
  }
}

lemma renamedPath_ensures(baseline: Option<string>, previous: string, next: string)
  ensures ((match baseline { case Some(i_) => false case None => true }) ==> (match renamedPath(baseline, previous, next) { case Some(i_) => false case None => true }))
  ensures (match baseline { case Some(i_baseline_val) => ((i_baseline_val == previous) ==> (match renamedPath(baseline, previous, next) { case Some(i_value) => (i_value == next) case None => false })) case None => true })
  ensures (match baseline { case Some(i_baseline_val) => ((i_baseline_val != previous) ==> (|i_baseline_val| >= |(previous + "/")| && i_baseline_val[..|(previous + "/")|] == (previous + "/")) ==> (match renamedPath(baseline, previous, next) { case Some(i_value) => (i_value == (next + i_baseline_val[|previous|..])) case None => false })) case None => true })
  ensures (match baseline { case Some(i_baseline_val) => ((i_baseline_val != previous) ==> !((|i_baseline_val| >= |(previous + "/")| && i_baseline_val[..|(previous + "/")|] == (previous + "/"))) ==> (match renamedPath(baseline, previous, next) { case Some(i_) => false case None => true })) case None => true })
{
}
