// Generated by lsc from reconcile-decisions.ts
// lsc options: string-semantics=javascript-utf16

datatype Option<T> = None | Some(value: T)

function conflict(local: Option<string>, incoming: Option<string>, base: Option<string>, hasBase: bool): bool
{
  (((!(hasBase) || (local != base)) && (!(hasBase) || (incoming != base))) && (local != incoming))
}

lemma conflict_ensures(local: Option<string>, incoming: Option<string>, base: Option<string>, hasBase: bool)
  ensures (!(hasBase) ==> (conflict(local, incoming, base, hasBase) == (local != incoming)))
  ensures (hasBase ==> (conflict(local, incoming, base, hasBase) == (((local != base) && (incoming != base)) && (local != incoming))))
{
}

function unchangedCheckpoint(hasBase: bool, hash: string, baseHash: string, path: Option<string>, basePath: Option<string>): bool
{
  ((hasBase && (hash == baseHash)) && (path == basePath))
}

lemma unchangedCheckpoint_ensures(hasBase: bool, hash: string, baseHash: string, path: Option<string>, basePath: Option<string>)
  ensures (unchangedCheckpoint(hasBase, hash, baseHash, path, basePath) == ((hasBase && (hash == baseHash)) && (path == basePath)))
{
}

function rebasedEdit(hasState: bool, hasPath: bool, hasDisk: bool, diskMatches: bool, remoteMatches: bool): bool
{
  ((((!(hasState) && hasPath) && hasDisk) && !(diskMatches)) && !(remoteMatches))
}

lemma rebasedEdit_ensures(hasState: bool, hasPath: bool, hasDisk: bool, diskMatches: bool, remoteMatches: bool)
  ensures (rebasedEdit(hasState, hasPath, hasDisk, diskMatches, remoteMatches) == ((((!(hasState) && hasPath) && hasDisk) && !(diskMatches)) && !(remoteMatches)))
{
}

function writeDisposition(hasBefore: bool, hasOwner: bool, equal: bool): string
{
  if ((hasBefore && !(hasOwner)) && !(equal)) then
    "blocked"
  else
    if equal then
      "unchanged"
    else
      "write"
}

lemma writeDisposition_ensures(hasBefore: bool, hasOwner: bool, equal: bool)
  ensures ((writeDisposition(hasBefore, hasOwner, equal) == "blocked") == ((hasBefore && !(hasOwner)) && !(equal)))
  ensures ((writeDisposition(hasBefore, hasOwner, equal) == "unchanged") == equal)
  ensures ((writeDisposition(hasBefore, hasOwner, equal) == "write") == (!(equal) && (!(hasBefore) || hasOwner)))
{
}
